name: Sync to Old Repo

on:
  push:
    branches:
      - main   # jalankan setiap push ke branch main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout new repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NEW_REPO_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to old repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add old git@github.com:rafkichanel/my-iptv-playlist.git
          git push old main --force
